AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dom-ria-scraper

  Sample SAM Template for dom-ria-scraper

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 256
    Environment:
      Variables:
        RIA_API_KEY: rt8cOYueGa9MszxZSIPsE7TGMXfkQC1vsFsJDacc
        S3_BUCKET: eu-central-1-scraper-data

Resources:
  DomRiaScraperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: scraper/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        DomRiaScraper:
          Type: Schedule # More info about Event: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
          Properties:
            Schedule: cron(0 6 * * ? *)
            Name: daily-run-dom-ria
            Description: Daily run at 06-00 am
            Enabled: True

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DomRiaScraperFunction:
    Description: "DomRiaScraper Lambda Function ARN"
    Value: !GetAtt DomRiaScraperFunction.Arn
  DomRiaScraperFunctionIamRole:
    Description: "Implicit IAM Role created for DomRiaScraper function"
    Value: !GetAtt DomRiaScraperFunctionRole.Arn
